#f1=input("enter fruit no 1")
#f2=input("enter fruit no 2")
#f3=input("enter fruit no 3")
#f4=input("enter fruit no 4")
#f5=input("enter fruit no 5")
#f6=input("enter fruit no 6")
#f7=input("enter fruit no 7")
#fruit_list=[f1,f2,f3,f4,f5,f6,f7]
#print(fruit_list)
m1=int(input("enter marks no 1"))
m2=int(input("enter marks no 2"))
m3=int(input("enter marks no 3"))
m4=int(input("enter marks no 4"))
m5=int(input("enter marks no 5"))
m6=int(input("enter marks no 6"))
marks=[m1,m2,m3,m4,m5,m6]
marks.sort()
print(marks)
